defaults:
  - _self_

data_path: "data/processed/${gitsha}/${ticker}/train.npz"
val_path: "data/processed/${gitsha}/${ticker}/val.npz"
base_ckpt: "google/timesfm-1.0-200m-pytorch"
lora_r: 8
ppo:
  rollout_batch_size: 64
  epochs: 3
  target_kl: 0.2
  clip_range: 0.2

