version: "3.8"

services:
  mlflow:
    image: mlflow/mlflow
    container_name: mlflow.internal
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: >
      mlflow server --host 0.0.0.0 --port 5000 \
        --backend-store-uri sqlite:///mlflow/mlflow.db \
        --default-artifact-root /mlflow/mlruns

# mlflow server --host 0.0.0.0 --port 5000 \
#         --backend-store-uri sqlite:///mlflow/mlflow.db \
#         --default-artifact-root /workspaces/.devcontainer/finfm/mlflow/mlruns